apiVersion: v1
kind: Service
metadata:
  name: egress-gateway
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: tcp
      name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    istio: egress-gateway
  sessionAffinity: None
  type: ClusterIP
